language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

script:
  - npm run stats && npm run build

deploy:
  provider: pages
  local_dir: /dist/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
